# Generated by Django 5.0.6 on 2024-05-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiseev_edu_docs_accounting_backend_app', '0002_rename_content_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
