# Generated by Django 5.0.6 on 2024-05-13 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiseev_edu_docs_accounting_backend_app', '0003_alter_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='moiseev_edu_docs_accounting_backend_app.student'),
        ),
    ]
